.TH SUP 1 sup\-VERSION
.SH NAME
sup - scale user privileges
.SH SYNOPSIS
.B sup
.RB [ \-l ]
.RI [ command
.RI [ arg ...]]
.SH DESCRIPTION
sup is a minimal privilege escalation utility that allows normal
users to run other programs as different user and group.
.P
The configuration is done in config.h at compile time.
.SH OPTIONS
.TP
.B \-l
list compiled authorizations
.SH AUTHOR
parazyd <parazyd@dyne.org>
