#!/bin/sh
#
# Copyright (c) 2018 Ivan J. <parazyd@dyne.org>
# See LICENSE file for copyright and license details.

input_pw() {
	yad \
		--title="Change the root password" \
		--text="<b>Change the root password</b>

Enter the root password which you wish to use:" \
		--no-escape \
		--borders=40 \
		--image="/usr/share/icons/Adwaita/64x64/apps/system-users-symbolic.symbolic.png" \
		--image-on-top \
		--center \
		--fixed \
		--width=360 \
		--height=100 \
		--entry \
		--button="<b>Accept</b>":0
}

pw=""
while [ -z "$pw" ]; do
	pw="$(input_pw)"
done

echo "root:${pw}" | chpasswd
