#!/bin/sh
#
# this will generate a random passphrase for the root password
# runs on boot through rc.local

## XXX: will be reintroduced after testing phase (1.0)
#pass="$(echo "$(shuf -n 2 /usr/share/dict/words --random-source=/dev/urandom | tr '\n' '-')")"
pass="toor"

echo "root:${pass}" | chpasswd
[ $? = 0 ] || return 1

cat <<EOF >> /home/luther/.zshrc
echo
echo "Welcome to heads!"
echo "-----------------"
echo "The root password is:"
echo "-----------------"
echo "${pass}"
echo "-----------------"
echo "You will not see it again"
echo
sed -i -e '/^zrclocal/q' /home/luther/.zshrc
EOF
