#!/bin/sh
#
# Copyright (c) Ivan J. <parazyd@dyne.org>
# See LICENSE file for copyright and license details.
#
# compile our custom linux kernel modules

compile_permakey() {
	cd /usr/src/permakey

	eval "$(cat usbdev | xargs udevadm info grep -E 'ID_VENDOR_ID|ID_MODEL_ID' | cut -d' ' -f2)"
	sed -i config.h -e "s/1234/$ID_VENDOR_ID/" -e "s/5678/$ID_MODEL_ID/"

	make 2>&1 >/dev/null && insmod permakey.ko
}

grep -q 'nopermakey' /proc/cmdline || compile_permakey

return 0
