#!/bin/sh
#
# Copyright (c) 2016-2018 Ivan J. <parazyd@dyne.org>
# See LICENSE file for copyright and license details.
#
# heads initial setup
# Inspired by the Tails welcome screen.

rm -f /etc/sudoers.d/heads-welcome

data="$(yad \
	--title="Welcome to heads!" \
	--text="Welcome to heads!
Here you can choose to customize your system before starting the graphical
environment. Select any option below to proceed." \
	--form \
	--columns=1 \
	--center \
	--no-escape \
	--separator=":" \
	--field="Select a keyboard layout!preferences-desktop-keyboard-symbolic":FBTN \
	--field="Set the computer language (locale)!preferences-desktop-locale-symbolic":FBTN \
	--field="Set the timezone!preferences-system-time-symbolic":FBTN \
	--field="Change the root password!system-users-symbolic":FBTN \
	--field="":LBL \
	--field="Miscellaneous options:":LBL \
	--field="Randomize MAC addresses of network interfaces":CHK \
	--button="Shutdown":1 \
	--button="Start heads":0 \
	"/usr/local/lib/heads/heads-keymap" \
	"/usr/local/lib/heads/heads-locale" \
	"/usr/local/lib/heads/heads-tz" \
	"/usr/local/lib/heads/heads-rootpw" \
	"n/a" \
	"n/a" \
	"TRUE")"

# Shut down on unsuccessful exit.
#[ $? = 0 ] || init 0

# $data:
# 0: layout
# 1: locale
# 2: timezone
# 3: rootpw
# 4: n/a
# 5: n/a
# 6: macaddr
i=-1
echo "$data" | tr ':' '\n' | while read val; do
	i=$(( $i + 1 ))
	case "$i" in
		6)
			[ "$val" = TRUE ] || continue
			cp -f /usr/local/share/heads/wicd-preconn \
				/etc/wicd/scripts/preconnect/macchange
			chmod 755 /etc/wicd/scripts/preconnect/macchange
			;;
		*)
			continue
			;;
	esac
done
