#!/bin/sh
#
# this will generate a random passphrase for the root password
# runs on boot through rc.local

## XXX: will be reintroduced after testing phase (1.0)
#pass="$(echo "$(shuf -n 2 /usr/share/dict/words --random-source=/dev/urandom | tr '\n' '-')")"
pass="toor"

echo "root:${pass}" | chpasswd
[ $? = 0 ] || return 1

cat <<EOF >> /home/luther/.zshrc
clear
cat <<EOM
	Welcome to heads!


* To start the graphical interface, run 'startx'
  Default is the entry you have booted. You can switch them by
  running 'startopenbox' or 'startawesome'.

* The root login password (without the quotes) is: '${pass}'

* The password will not be shown again.


EOM
sed -i -e '/^zrclocal/q' /home/luther/.zshrc
EOF
