#!/bin/sh
#
# Copyright (c) 2016-2018 Ivan J. <parazyd@dyne.org>
# See LICENSE file for copyright and license details.

cd /usr/src/sup

cat <<EOF > config.h
#define SETUID 0
#define SETGID 0

static struct rule_t rules[] = {

	{ 1000, "heads-init", "/usr/local/bin/heads-init",
		"$(sha256sum /usr/local/bin/heads-init | cut -d' ' -f1)" },

	{ 1000, "heads-generate-debug", "/usr/local/bin/heads-generate-debug",
		"$(sha256sum /usr/local/bin/heads-generate-debug | cut -d ' ' -f1)" },
};
EOF

make clean install
