#!/bin/sh
#
# Copyright (c) 2016-2018 Ivan J. <parazyd@dyne.org>
# See LICENSE file for copyright and license details.
#
# this will generate a random passphrase for the root password
# runs on boot through rc.local

pass="$(echo "$(shuf -n 2 /usr/share/dict/words --random-source=/dev/urandom | tr '\n' '-' | rev | cut -c 2- | rev)")"
#pass="toor"

echo "root:${pass}" | chpasswd
[ $? = 0 ] || return 1
